force-app/main/default/objects/ABRA_Flexi_Data_Integration_Settings__c/ABRA_Flexi_Data_Integration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds data integration parameters and endpoints.</description>
    <label>ABRA Flexi Data Integration Settings</label>
</CustomObject>

force-app/main/default/objects/ABRA_Flexi_Data_Integration_Settings__c/fields/Order_Data_Integration_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Order_Data_Integration_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines whether data synchronisation for Order objects is Active.</description>
    <inlineHelpText>Determines whether data synchronisation for Order objects is Active.</inlineHelpText>
    <label>Order Data Integration Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AbraOrderDataSyncService.cls
/**
 * 
 *
 * @author  tomaschour - Aspectworks
 * @date    2021-04-28
 */
public with sharing class AbraOrderDataSyncService implements AbraSynchronizationInterface{

    public void exportRecords(List<SObject> records, Map<String, Object> params) {
        if ((Boolean) AbraFlexiDataIntegrationSettings.getAttributeValue(ABRA_Flexi_Data_Integration_Settings__c.Order_Data_Integration_Is_Active__c)) {
            AbraUtils.exportSObjects(records, String.valueOf(params.get(AbraUtils.ABRA_OBJECT_NAME_PARAM )));
        }
    }

}