force-app/main/default/objects/ABRA_Flexi_Data_Mapping__mdt/ABRA_Flexi_Data_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Defines data mapping between Salesforce and ABRA FlexiBee</description>
    <label>ABRA Flexi Data Mapping</label>
    <pluralLabel>ABRA Flexi Data Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/ABRA_Flexi_Data_Mapping__mdt/fields/ABRA_Flexi_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>ABRA_Flexi_Entity_Name__c</fullName>
    <description>Defines name of entity in ABRA for which mapping is.</description>
    <inlineHelpText>Defines name of entity in ABRA for which mapping is.</inlineHelpText>
    <label>ABRA Flexi Entity Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABRA_Flexi_Data_Mapping__mdt/fields/ABRA_Flexi_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>ABRA_Flexi_Field_Name__c</fullName>
    <description>Name of field in ABRA Flexi.</description>
    <inlineHelpText>Name of field in ABRA Flexi.</inlineHelpText>
    <label>ABRA Flexi Field Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABRA_Flexi_Data_Mapping__mdt/fields/ABRA_Flexi_To_SFSC_Sync__c.field-meta.xml
<CustomField>
    <fullName>ABRA_Flexi_To_SFSC_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether data for this field should be synchronised from ABRA Flexi into SFSC.</description>
    <inlineHelpText>Determines whether data for this field should be synchronised from ABRA Flexi into SFSC.</inlineHelpText>
    <label>ABRA Flexi To SFSC Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ABRA_Flexi_Data_Mapping__mdt/fields/SFSC_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>SFSC_Field_Name__c</fullName>
    <description>API Name of Field in Salesforce</description>
    <inlineHelpText>API Name of Field in Salesforce</inlineHelpText>
    <label>SFSC Field Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABRA_Flexi_Data_Mapping__mdt/fields/SFSC_SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SFSC_SObject_Name__c</fullName>
    <description>Defines name of SObject for which mapping is.</description>
    <inlineHelpText>Defines name of SObject for which mapping is.</inlineHelpText>
    <label>SFSC SObject Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ABRA_Flexi_Data_Mapping__mdt/fields/SFSC_To_ABRA_Flexi_Sync__c.field-meta.xml
<CustomField>
    <fullName>SFSC_To_ABRA_Flexi_Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines whether data for this field should be synchronised from SFSC into ABRA Flexi.</description>
    <inlineHelpText>Determines whether data for this field should be synchronised from SFSC into ABRA Flexi.</inlineHelpText>
    <label>SFSC To ABRA Flexi Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AbraMappingManagementController.cls
/**
 * 
 *
 * @author  tomaschour - Aspectworks
 * @date    2021-04-30
 */
public with sharing class AbraMappingManagementController {

    @AuraEnabled
    public static List<MappingDto> getCurrentMappings(String abraEntityName) {
        List<MappingDto> dtos = new List<MappingDto>();
        Map<String, ABRA_Flexi_Data_Mapping__mdt> mappings = IntegrationSObjectUtils.getAllMappingsByAbraAttributeName(abraEntityName);
        for(ABRA_Flexi_Data_Mapping__mdt mapping : mappings.values()) {
            dtos.add(new MappingDto(mapping));
        }
        return dtos;
    }

    @AuraEnabled
    public static XmlUtils.AbraEntityDefinitionDto getAbraFields(String abraEntityName) {
        List<Dom.XmlNode> fieldDefinitionNodes = AbraFlexiConnector.getImportSchema(abraEntityName);
        return XmlUtils.getEntityDefinitionFromXsd(fieldDefinitionNodes, abraEntityName);
    }

    public class MappingDto{
        @AuraEnabled public Id recordId;
        @AuraEnabled public String sfscSObjectName;
        @AuraEnabled public String abraEntityApiName;
        @AuraEnabled public String sfscFieldName;
        @AuraEnabled public String abraFieldName;
        @AuraEnabled public Boolean sfscToAbraSync;
        @AuraEnabled public Boolean abraToSfscSync;
        @AuraEnabled public String ident;

        public MappingDto(ABRA_Flexi_Data_Mapping__mdt mapping) {
            this.recordId = mapping.Id;
            this.sfscSObjectName = mapping.SFSC_SObject_Name__c;
            this.abraEntityApiName = mapping.ABRA_Flexi_Entity_Name__c;
            this.sfscFieldName = mapping.SFSC_Field_Name__c;
            this.abraFieldName = mapping.ABRA_Flexi_Field_Name__c;
            this.sfscToAbraSync = mapping.SFSC_To_ABRA_Flexi_Sync__c;
            this.abraToSfscSync = mapping.ABRA_Flexi_To_SFSC_Sync__c;
            this.ident = mapping.Id;
        }
    }

}